# Generated by Django 2.1.3 on 2019-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(default=0, verbose_name='Id User')),
                ('first_name', models.CharField(max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('password_user', models.CharField(max_length=250, verbose_name='Password User')),
                ('username', models.CharField(max_length=250, verbose_name='Username')),
                ('type_user', models.CharField(max_length=1, verbose_name='Type User')),
                ('registration_date', models.DateField(max_length=250, verbose_name='Registration Date')),
                ('birthdate', models.DateField(max_length=250, verbose_name='Birthdate')),
                ('phone', models.DateField(max_length=250, verbose_name='Phone')),
                ('sex', models.DateField(max_length=250, verbose_name='Gender')),
                ('version_number', models.IntegerField(default=0, verbose_name='Version Number')),
            ],
        ),
    ]
