# Generated by Django 2.1.3 on 2019-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUsers',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=50)),
                ('type_user', models.CharField(max_length=1)),
                ('registration_date', models.DateField()),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('version_number', models.IntegerField()),
            ],
            options={
                'db_table': 'ausers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AUsersWithouID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=50)),
                ('type_user', models.CharField(max_length=1)),
                ('registration_date', models.DateField()),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('version_number', models.IntegerField()),
            ],
            options={
                'db_table': 'ausers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id_event', models.IntegerField(primary_key=True, serialize=False)),
                ('name_event', models.CharField(max_length=250)),
                ('theme_event', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField()),
                ('location_map', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('address_event', models.TextField(blank=True, null=True)),
                ('size_hosting', models.IntegerField(blank=True, null=True)),
                ('state_event', models.CharField(blank=True, max_length=50, null=True)),
                ('description_event', models.TextField(blank=True, null=True)),
                ('type_event', models.CharField(max_length=50)),
                ('version_number', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventsWithoutID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=250)),
                ('theme_event', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField()),
                ('location_map', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('address_event', models.TextField(blank=True, null=True)),
                ('size_hosting', models.IntegerField(blank=True, null=True)),
                ('state_event', models.CharField(blank=True, max_length=50, null=True)),
                ('description_event', models.TextField(blank=True, null=True)),
                ('type_event', models.CharField(max_length=50)),
                ('version_number', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participations',
            fields=[
                ('id_participation', models.IntegerField(primary_key=True, serialize=False)),
                ('participation_date', models.DateField()),
            ],
            options={
                'db_table': 'participations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipationsWithouID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_date', models.DateField()),
            ],
            options={
                'db_table': 'participations',
                'managed': False,
            },
        ),
    ]
