# Generated by Django 2.1.3 on 2019-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_user',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.DateField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.DateField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='version_number',
            field=models.IntegerField(default=0),
        ),
    ]
